apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  project: default
  source:
    repoURL: 'https://github.com/kehe0014/springboot-microservices-gitops.git'
    targetRevision: HEAD
    path: infrastructure/base/nginx-ingress/nginx-ingress-chart
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - '.spec.template.spec.containers[] | select(.name == "controller") | .image'