---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api-gateway
          image: tdksoft341/api-gateway:latest
