apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
  type: helm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-repo-cm
  namespace: argocd
data:
  name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
  type: helm