apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  # Increase the number of replicas for high availability
  replicas: 3
  template:
    spec:
      containers:
        - name: product-service
          # Use a specific, stable production image tag
          image: your-image-repository/product-service:1.0.0
          # Increase resource requests and limits for production
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
