apiVersion: v2
name: api-gateway
description: A Helm chart for API Gateway service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: spring-boot
    version: "0.2.0"
    repository: "https://helm.springframework.cloud/"
    condition: spring-boot.enabled
