# Default values for api-gateway
replicaCount: 1

image:
  repository: tdksoft341/api-gateway
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

spring-boot:
  enabled: true
  config:
    application.properties: |
      server.port=8080
      spring.application.name=api-gateway

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"
